ONNC/onnc

README.md

Reference:
https://medium.com/@onnc/open-neural-network-compiler-onnc-3f7dcfe8fc8f

Revise wording

---

lib/IR/Compute/Value.cpp
tools/unittests/ComputeIRTest.cpp

root cause: replaceInput will modify m_UseList iterator.

fix Value::replaceAllUsesWith bug

---

lib/Target/Sophon/BM188x/BM188xBackend.cpp
lib/Target/Sophon/BM188x/UpdateCtablePass.cpp

This is prototyping code
i will refactoring it to using visitor pattern later.
Thanks.

Sophon: porting UpdateCtablePass to ComputeIR

---

lib/Target/Sophon/BM188x/Compute/Conv.cpp
lib/Target/Sophon/BM188x/Compute/Conv.h
lib/Target/Sophon/BM188x/Lowers/ConvLower.cpp

quantize pass would replace input value with new one
so need to save index for optional input value.

Sophon: fix Conv and Conv Lowering bug

---

lib/Target/Sophon/BM188x/Lowers/ScaleLower.cpp
lib/Target/Sophon/BM188x/Lowers/SumLower.cpp

Sophon: add target-dep lower

---

lib/Target/Sophon/BM188x/GenWeightPass.cpp

Sophon: fix default file extension

---

lib/Target/Sophon/BM188x/CodeEmitVisitor.cpp
lib/Target/Sophon/BM188x/Compute/LRN.h
lib/Target/Sophon/BM188x/UpdateCtablePass.cpp

Sophon: UpdateCtablePass, Support more operator

---

lib/Target/Sophon/BM188x/GenRuntimeInfoPass.cpp

work around the unknown seg fault issue.
Thanks!

Sophon: fix output file seg fault issue

---

lib/Target/Sophon/BM188x/BM188xBackend.cpp
lib/Target/Sophon/BM188x/BM188xEncodeInstsPass.cpp
lib/Target/Sophon/BM188x/BM188xEncodeInstsPass.h
lib/Target/Sophon/BM188x/CMakeLists.txt

extract BM188xEncodeInstructions from BM188xBackend.cpp as new pass.
Thanks.

Sophon: add BM188xEncodeInstsPass

---

lib/Target/Sophon/BM188x/BM188xBackend.cpp
lib/Target/Sophon/BM188x/Tests/BackendTest.cpp
lib/Target/Sophon/BuildMemOpndPass.cpp

Sophon: support Flatten operator

---

lib/IR/CMakeLists.txt
lib/Transforms/CMakeLists.txt

[CMakeLists] add FlattenLower.cpp/Flatten.cpp

---

lib/Target/Sophon/BM188x/BM188xBackend.cpp
lib/Target/Sophon/BM188x/BM188xBackend.h
lib/Target/Sophon/BM188x/CMakeLists.txt
lib/Target/Sophon/BM188x/Compute/Concat.cpp
lib/Target/Sophon/BM188x/Compute/Concat.h
lib/Target/Sophon/BM188x/UpdateCtablePass.cpp
lib/Target/Sophon/BM188x/UpdateVisitor.cpp
lib/Target/Sophon/BM188x/UpdateVisitor.h

1. Refactor updateCtablePass to using visitor pattern
2. support more operators
Thanks!

Sophon: Refactor and support more operators in updateCtablePass 

---

lib/Target/Sophon/BM168x/TGConv.h
lib/Target/Sophon/BM168x/TGGemm.h
lib/Target/Sophon/BM168x/TGLRN.h
lib/Target/Sophon/BM168x/TGMaxPool.h
lib/Target/Sophon/BM168x/TGRelu.h
lib/Target/Sophon/BM168x/TGSoftmax.h
lib/Target/Sophon/BM188x/BM188xComputeOperator.h
lib/Target/Sophon/BM188x/Weight.h
lib/Target/Sophon/CMakeLists.txt
lib/Target/Sophon/ComputeOperator2.cpp
lib/Target/Sophon/ComputeOperator2.h
lib/Target/Sophon/TGBackend.h
lib/Target/Sophon/TargetLowering.h

Sophon: change legacy code naming to avoid ambiguous

---

lib/Target/Sophon/BM188x/BM188xBackend.cpp
lib/Target/Sophon/BM188x/BM188xVisitor.h
lib/Target/Sophon/BM188x/CMakeLists.txt
lib/Target/Sophon/BM188x/CodeEmitVisitor.cpp
lib/Target/Sophon/BM188x/CodeEmitVisitor.h
lib/Target/Sophon/BM188x/Compute/BMScale.cpp
lib/Target/Sophon/BM188x/Compute/BMScale.h
lib/Target/Sophon/BM188x/FillWeightVisitor.cpp
lib/Target/Sophon/BM188x/FillWeightVisitor.h
lib/Target/Sophon/BM188x/Lowers/BMScaleLower.cpp
lib/Target/Sophon/BM188x/Lowers/BMScaleLower.h
lib/Target/Sophon/BM188x/Lowers/ScaleLower.cpp
lib/Target/Sophon/BM188x/UpdateVisitor.cpp
lib/Target/Sophon/BM188x/UpdateVisitor.h

Sophon: add BMScale operator

---

lib/Target/Sophon/BM188x/Compute/Transpose.cpp

Sophon: add assert check for Transpose op

---

README.md

Specify the version of external library in ONNC.

Update README.md to point out the version of external library.

---

.travis.yml
CMakeLists.txt

There's no checking for building error with push request.
I configured it with Travis CI.

Check building error of push request

---

include/onnc/Analysis/UpdateGraphOutputSize.h
lib/Analysis/UpdateGraphOutputSize.cpp

This is done by onnx 1.3 shape inference.

Remove unused pass (done by onnx).

---

include/onnc/Target/TargetBackend.h
lib/Target/TargetBackend.cpp
lib/Target/X86/X86Backend.cpp

As title.
Provides a standard way to build up standard ONNC/Compute IR.

Add helper function for standard Tensor selection.

---

CMakeLists.txt
cmake/check.cmake
lib/Support/Unix/Timer.inc

We should rewrite/improve Timer later.
This PR is for the record.

Fix Timer related issues

---

CONTRIBUTING.md
README.md

Add basic rule of how to contribute code.

---

tools/unittests/main.cpp

Merge this after CI image upgraded.

Upgrade SkyPat.

---

include/onnc/IR/CodeEmit.h
include/onnc/IR/Quadruple.h
lib/IR/CodeEmit.cpp
lib/IR/Quadruple.cpp
lib/Makefile.am
lib/Target/Vanilla/CodeEmitVisitor.cpp
lib/Target/Vanilla/CodeEmitVisitor.h
lib/Target/Vanilla/Makefile.am
lib/Target/Vanilla/TargetInfo/VanillaTargetInfo.cpp
lib/Target/Vanilla/TargetInfo/VanillaTargetInfo.h
lib/Target/Vanilla/TargetInfo/VanillaTargetMemInfo.cpp
lib/Target/Vanilla/TargetInfo/VanillaTargetMemInfo.h
lib/Target/Vanilla/VanillaBackend.cpp
lib/Target/Vanilla/VanillaBackend.h

This vanilla backend can be executed by the command
$ ./onnc model.onnx -mquadruple vanilla
Then generates some dummy machine codes. 
Backend developers can jump-start their work from such a skeleton.

Add vanilla backend

---

include/onnc/Target/TargetTransformInfo.h

We already have cost model query interface for onnx node, add similar ones for onnc IR

[TargetTransformInfo] Add cost model interface for onnc IR

---

README.md

In this patch I corrected the link in README.md.

Fixes #104 - Corrected the contribution guideline link in README.md

---

include/onnc/IR/Compute/Initializer.h
include/onnc/IR/Compute/InputOperator.h
include/onnc/IR/Compute/OutputOperator.h
lib/IR/Compute/Initializer.cpp
lib/IR/Compute/InputOperator.cpp
lib/IR/Compute/OutputOperator.cpp
lib/IR/ComputeGraph.cpp
lib/IR/ComputeOperator.cpp
lib/Target/X86/CMakeLists.txt
lib/Target/X86/Compute/X86ConvRelu.cpp
lib/Target/X86/Compute/X86ConvRelu.h
lib/Target/X86/Makefile.am
lib/Target/X86/X86Backend.cpp
lib/Target/X86/X86FuseConvRelu.cpp
lib/Target/X86/X86FuseConvRelu.h
tools/unittests/MemAllocTest.cpp

This PR merge the example of how to use fused IR made by CY.
https://github.com/cycheng/onnc/commit/bac9a11a786535e465bfc4ec64844030da061bc4
I also disable the pass named CreateX86FuseConvReluPass since it doesn't really work so far.

Research public with fused IR

---

include/onnc/Config/Config.h.cmake.in
lib/IR/CMakeLists.txt
lib/Target/Vanilla/CMakeLists.txt

Fix Vanilla backend on cmake.

---

CONTRIBUTING.md

Fix CONTRIBUTING.md markdown link,
Otherwise, you will get the `Not Found` error at browser.

fix CONTRIBUTING.md markdown link

---

lib/Target/NvDla/CodeEmitVisitor.cpp
lib/Target/NvDla/NvDlaDefine.h
lib/Target/NvDla/NvDlaMemInfoPass.cpp
lib/Target/NvDla/NvDlaMeta.cpp
lib/Target/NvDla/NvDlaMeta.h
lib/Target/NvDla/fp16.c

`[Problem]`  
There are some magic numbers related to hardware configuration.
But it's hard to understand their business logic from source code.
`[Solution]`  
Introduce macros and give the magic numbers meaningful names

Fix: replace magic numbers by pre-defined macros

---

docs/ONNC-Utilities.md

delete "a", modify "accross"->across

Fix typo in ONNC-Utilities.md #7

---

docs/ONNC-IR-Extension-Guide.md

modify "Code Sample 3" to "Code Snippet 3"

modify statement on ONNC-IR-Extension-Guide.md

---

scripts/create-new-backend.sh

Update create-new-backend.sh for naming consistency

---

docs/ONNC-Backend-Porting-Guide.md
docs/ONNC-IR-Extension-Guide.md
docs/ONNC-Utilities.md

We can merge it later since there might be more fixes for the documents.

Merge the branch `docs` to `master`
